package com.ucuenca.gestion.models.enums;

public enum TipoArchivoPDF {
    T1_FORMULARIO_1_PLAN,
    T2_FORMULARIO_2_RUBRICA,
    T3_FORMULARIO_3_INFORME,
    T4_OFICIO_SOLICITUD_PROP_INICIAL,
    T5_OFICIO_PRESENTACION_PROP_VUELTA,
    T6_CARTA_COMPROMISO,
    T7_PLANTILLA_FORMATO_OFERTA,
    T8_SOLICITUD_CONVENIO_MARCO,
    T9_MALLA_ACADEMICA,
    T10_CURRICULUM_VITAE
}
