# Configuración de Base de Datos - GestionPracticas
db.default.driver=org.postgresql.Driver
db.default.url=jdbc:postgresql://localhost:5432/gestion_practicas
db.default.user=postgres
db.default.password=postgres

# Configuración del Pool de Conexiones
db.default.poolInitialSize=5
db.default.poolMaxSize=10
db.default.poolConnectionTimeoutMillis=1000
db.default.poolValidationQuery=select 1
